### ISSUE TITLE
Cannot format date or datetime axis

### ISSUE THREAD

**Issue by gabrielfeo** [Kotlin/ggdsl#121]
I'm running into errors trying to format a LocalDate axis.

When using `java.time.LocalDate`, [a part of ggdsl requires limits to be numbers](https://github.com/Kotlin/ggdsl/blob/0a562058ce512e089645a0ac0d5a6dc38bc094aa/ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/translator/util.kt#L40). See [a sample notebook](https://gist.github.com/gabrielfeo/eb64564d6f88be86631eb3bebf86edd0#file-ggdsl_datetime_errors_javatime-ipynb).

After seeing how ggdsl only checks for `kotlinx.datetime` types (which is unexpected because [lets-plot-kotlin only seems to supports java.time](https://github.com/JetBrains/lets-plot-kotlin/blob/master/plot-api/src/jvmTest/kotlin/org/jetbrains/letsPlot/DataSeriesTimeStandardizeTest.kt)), I tried using `kotlinx.datetime.LocalDate` instead. However, lets-plot fails under the hood by not recognizing the date type. See [a sample notebook](https://gist.github.com/gabrielfeo/eb64564d6f88be86631eb3bebf86edd0#file-ggdsl_datetime_errors_kotlinx-ipynb).

Is there a recommended way of formatting a datetime axis?

**Comment by AndreiKingsley** [comment]
Hi! Improved support for `kotlinx.datetime` types will be released in the next version. However, lets-plot-kotlin still doesn't fully support datetime, especially `LocalDate`, so I would recommend using `Instant` or `LocalDateTime`.
I will answer later and send an example after the next release

**Comment by gabrielfeo** [comment]
Hi! Thank you. Using `Instant` does work 🙂
